apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: babycsrf
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
      - protocol: "HTTPS"
        targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
