apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: socat
spec:
  deployed: true
  powDifficultySeconds: 10
  network:
    public: false
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: kind/healthcheck:c64d96ef8b6b6388c1e3011e03d5f567342e9730c2b856d3a84014b6d63bc465
  image: kind/challenge:b99eeecaf4995226e798eee424192f056e8f6c70a517616afafc3882683bfeb2
